name: 'toki0436'

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install beautifulsoup4
          pip install PyGithub
          pip install requests
          pip install python-telegram-bot
      - name: Run Crawler
        run: |
          python toki0436.py
